### ISSUE TITLE
Tempo fails -- long paths overflow string?

### ISSUE THREAD

**Issue by joerivanleeuwen** [AA-ALERT/spack#1]
Leon notes that the current TEMPO fails at runtime. Probably the temp files that is needs cannot be accessed because the path in TEMPO have hard coded lengths that are too short. 

We've seen this in the past for LOFAR data. There is was fixed in this version:
  https://github.com/lbaehren/lofarsoft/blob/master/src/Pulsar/external/tempo/tempo-20120213.tar.gz

@gijzelaerr to look into it?

**Comment by gijzelaerr** [comment]
issue confirmed with version ce072d2 from sourceforge. tempo can only handle paths up to 80 chars. to replicate run from fresh checkout:

```
$ ./prepare
$ make
$ mkdir /tmp/tempo-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
$ cp tempo.hlp /tmp/tempo-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
$ TEMPO=/tmp/tempo-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa src/tempo
```

**Comment by gijzelaerr** [comment]
this is also still an issue with the latest maser 13e12c2a89757937fb825ce3b61baba14b76bd92  Tue Apr 24 16:08:18 2018 -0600

**Comment by gijzelaerr** [comment]
The issue seems to have been solved in the 20120213 version on the lofarsoft github repo. Code diverged significantly in the meanwhile though.

**Comment by gijzelaerr** [comment]
i made a cmake file for tempo https://gist.github.com/gijzelaerr/d67cbbb37ea95e2623146bbe4c45bd99

**Comment by gijzelaerr** [comment]
Ok found the issue. sourceforge doens't allow pull requests, so I pushed a mirror of tempo to github:

https://github.com/AA-ALERT/tempo/

The fix should be in the PR:

https://github.com/AA-ALERT/tempo/pull/2

I've also added a PR for the cmake file:

https://github.com/AA-ALERT/tempo/pull/1

**Comment by gijzelaerr** [comment]
@loostrum it looks like you already patch for the path length issue?:

https://github.com/AA-ALERT/spack/blob/master/packages/tempo/package.py#L23

**Comment by loostrum** [comment]
@gijzelaerr My commit fixed part of the problem, but not all of it. Seems like your PR does, I'll try it out

**Comment by loostrum** [comment]
@gijzelaerr I installed the fix_path_length branch of your TEMPO mirror and that one works.

**Comment by gijzelaerr** [comment]
fixed per https://github.com/AA-ALERT/spack/commit/a787b2f8e7aca486e9e3490453df91972aa93350
