### ISSUE TITLE
psrchive is incomplete

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/spack#22]
I've installed psrchive on ARTS, but some binaries are missing. E.g. `psrplot` and `pazi`. Maybe not coincidentally these both are interactive tools that use X11.

The package also contains python bindings, that only get compiled when passing `--enable-shared` to configure. Maybe that could be added as a variant?

**Comment by gijzelaerr** [comment]
psrchive is now compiled as shared library by default (triggering compiling of python module).

Compilation of GUI can be triggered by adding `+x11` to the spack install, but be prepared to wait for while since it depends on X11 and QT.
