### ISSUE TITLE
PRESTO does not compile anymore

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/spack#23]
With current master (567e8be98d027143ea04c97fed6f9cd3faa1c22f)
Seems like there is an issue with `PGPLOT_DIR`, as it cannot find `cpgplot.h`:
```  >> 145    /opt/spack/var/spack/stage/presto-2.1-kiufbsbculpagynonz3thzmvd6w2n3mo/presto-2.1//include/plot2d.h:1:
            21: fatal error: cpgplot.h: No such file or directory
     146     #include "cpgplot.h"```

**Comment by gijzelaerr** [comment]
ach, i've modifed pgplot to set that environment variable, which is maybe a bit fragile.

you can problaby solve this to recompile/update pgplot.

**Comment by gijzelaerr** [comment]
@loostrum can you verify that updating/recompiling pgplot solves this presto compilation issue?

**Comment by loostrum** [comment]
@gijzelaerr It still does not work, but I found the issue: the `cpgplot.h` file is currently at `$PGPLOT_DIR/cpgplot.h`, while that should be `$PGPLOT_DIR/include/cpgplot.h`
So if you could change the pgplot package to copy file to the include dir, it should work.

**Comment by gijzelaerr** [comment]
that is weird, i'm curious why it worked for me then... ah well. spack.

**Comment by gijzelaerr** [comment]
should be solved now.
