### ISSUE TITLE
TEMPO fails at runtime

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/spack#25]
`Error opening Observatory file: /opt/spack/var/spack/stage/tempo-2018-04-24-eys5yoahyqlz633ffwxfuwb2tbhtcjgz/tempo/obsys.dat `

For some reason it searches in the _stage_ directory, even though `$TEMPO` points to the correct location: `/opt/spack/opt/spack/linux-centos7-x86_64/gcc-6.4.0/tempo-2018-04-24-eys5yoahyqlz633ffwxfuwb2tbhtcjgz/tempo`

**Comment by gijzelaerr** [comment]
so there are 2 prefixes, one for build time and one for runtime. They are mixed up here.

**Comment by gijzelaerr** [comment]
actually, I was prepending to the building path, while we should override it.

**Comment by loostrum** [comment]
I'm still getting the same error.

**Comment by gijzelaerr** [comment]
What command are you running? I just tried to jjust run `tempo` adn that seems to work

**Comment by loostrum** [comment]
Try `tempo bary.txt` ([bary.txt](https://github.com/AA-ALERT/spack/files/2145338/bary.txt))

**Comment by gijzelaerr** [comment]
looks like we need to update the `tempo.cfg` in the tempo folder.

**Comment by gijzelaerr** [comment]
ok, writing config file now https://github.com/AA-ALERT/spack/commit/1dcd47a77dfab62a0dde49424d20890d227977aa. The error now is:

```
[molenaar@arts041 ~]$ tempo bary.txt 
 Cannot open leap.sec
```

**Comment by gijzelaerr** [comment]
leap.sec is found in `clock` folder, but also after copying it to `$TEMPO` it doesn't work...

**Comment by loostrum** [comment]
I'll check the layout of $TEMPO on a different system, maybe something is
in the wrong place

2018-06-28 17:26 GMT+02:00 Gijs Molenaar <notifications@github.com>:

**Comment by loostrum** [comment]
Okay, it may be a path length issue. It works fine if I copy $TEMPO from spack to e.g. my home folder and change tempo.cfg and $TEMPO accordingly. Output should be something like the following:

 ```TEMPO v 13.000 Princeton/ATNF Pulsar Collaboration
 Data from bary.txt

    N       MJD       Residual (p)  Residual (us)  Iteration (of 1)

      1 58213.22320590   0.000000          0.000            1
     11 58213.22552071   0.015681      15680.617            1
     21 58213.22771979   0.030575      30574.708            1
     22 58213.22783553   0.031359      31359.009            1

 Weighted RMS residual: pre-fit  9781.112 us. Predicted post-fit     0.369 us.
```

**Comment by gijzelaerr** [comment]
this issue seems to be fixed in the latest commit, enjoy!
