### ISSUE TITLE
TEMPO2 plk missing

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/spack#26]
TEMPO2 is missing the graphical `plk` plugin, probably needs X11 to be compiled. 
Maybe add a variant that includes X11-dependent tools?

**Comment by gijzelaerr** [comment]
how would you normally do this? i've added a `+x11` variant now, that configures tempo2 with `--with-x` enabled, but i still don't see a plk plugin.

**Comment by loostrum** [comment]
For me TEMPO2 was able to find X11 on its own, and just running make
plugins did compile plk.
Not sure why it won't work here

2018-06-28 17:36 GMT+02:00 Gijs Molenaar <notifications@github.com>:

**Comment by gijzelaerr** [comment]
fixed. to get all features install with `+x11 +gsl`
