### ISSUE TITLE
Add heimdall package

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/spack#29]
`https://git.code.sf.net/p/heimdall-astro/code`

Depends on cuda and dedisp. Configure with `--with-dedisp-dir=foo`

**Comment by gijzelaerr** [comment]
added file, but currently it doesn't compile due to an upstream bug:
```
     353    /home/molenaar/spack/lib/spack/env/gcc/g++ -DHAVE_CONFIG_H -I. -I/home/molenaar/spack/var/spack/stage/heimdall-astro-2018-05 
            -25-hv3jyjjudkomxwcbogtdhcivq32ijizh/code/Applications -I.. -I/home/molenaar/spack/var/spack/stage/heimdall-astro-2018-05-25 
            -hv3jyjjudkomxwcbogtdhcivq32ijizh/code/src -I../ -I../Formats -I../Network -I../Pipeline -I/home/molenaar -I/home/molenaar/s 
            pack/opt/spack/linux-centos7-x86_64/gcc-6.4.0/psrdada-2018-06-06-kn7ipe3ajnqmmxbfkjfkjcbywa7pelrq/include -I/home/molenaar/s 
            pack/opt/spack/linux-centos7-x86_64/gcc-6.4.0/dedisp-2017-11-27-wsszhbt6xe3cptxhsiylgtin5tsoj22k/include   -g -O2   -MT gene 
            rate_dmlist.o -MD -MP -MF $depbase.Tpo -c -o generate_dmlist.o generate_dmlist.C &&\                                         
     354    mv -f $depbase.Tpo $depbase.Po                                                                                               
     355    generate_dmlist.C: In function ‘int main(int, char**)’:                                                                      
  >> 356    generate_dmlist.C:101:46: error: ‘dedisp_generate_dm_list_guru’ was not declared in this scope                               
     357                                         &dm_count);    
```

**Comment by gijzelaerr** [comment]
and when i try to compile manually```
make[2]: Entering directory `/home/molenaar/upstream/heimdall-astro-code/Applications'
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2  -I/home/molenaar/spack/opt/spack/linux-centos7-x86_64/gcc-6.4.0/cuda-9.2.88-esi2xgqun5kfybd2mzuuore62cpuqqcy/include   -o heimdall heimdall.o ../Formats/libhdformats.la ../Pipeline/libhdpipeline.la ../Network/libhdnetwork.la -L/home/molenaar/spack/opt/spack/linux-centos7-x86_64/gcc-6.4.0/cuda-9.2.88-esi2xgqun5kfybd2mzuuore62cpuqqcy/lib64 -lcudart
libtool: link: g++ -g -O2 -I/home/molenaar/spack/opt/spack/linux-centos7-x86_64/gcc-6.4.0/cuda-9.2.88-esi2xgqun5kfybd2mzuuore62cpuqqcy/include -o heimdall heimdall.o  ../Formats/.libs/libhdformats.a ../Pipeline/.libs/libhdpipeline.a ../Network/.libs/libhdnetwork.a -L/home/molenaar/spack/opt/spack/linux-centos7-x86_64/gcc-6.4.0/cuda-9.2.88-esi2xgqun5kfybd2mzuuore62cpuqqcy/lib64 -lcudart
../Pipeline/.libs/libhdpipeline.a(pipeline.o): In function `hd_destroy_pipeline':
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:924: undefined reference to `dedisp_destroy_plan'
../Pipeline/.libs/libhdpipeline.a(pipeline.o): In function `hd_create_pipeline':
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:165: undefined reference to `dedisp_create_plan'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:172: undefined reference to `dedisp_generate_dm_list'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:182: undefined reference to `dedisp_enable_adaptive_dt'
../Pipeline/.libs/libhdpipeline.a(pipeline.o): In function `hd_execute':
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:321: undefined reference to `dedisp_get_channel_count'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:322: undefined reference to `dedisp_get_dt'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:323: undefined reference to `dedisp_get_f0'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:324: undefined reference to `dedisp_get_df'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:327: undefined reference to `dedisp_get_dm_count'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:328: undefined reference to `dedisp_get_dm_list'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:330: undefined reference to `dedisp_get_dt_factors'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:349: undefined reference to `dedisp_set_killmask'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:351: undefined reference to `dedisp_get_max_delay'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:408: undefined reference to `dedisp_execute_adv'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/pipeline.cu:359: undefined reference to `dedisp_get_max_delay'
../Pipeline/.libs/libhdpipeline.a(error.o): In function `throw_dedisp_error':
/home/molenaar/upstream/heimdall-astro-code/Pipeline/error.C:66: undefined reference to `dedisp_get_error_string'
../Pipeline/.libs/libhdpipeline.a(clean_filterbank_rfi.o): In function `apply_manual_killmasks(dedisp_plan_struct*, int*, unsigned int, hd_range*)':
/home/molenaar/upstream/heimdall-astro-code/Pipeline/clean_filterbank_rfi.cu:507: undefined reference to `dedisp_get_channel_count'
../Pipeline/.libs/libhdpipeline.a(clean_filterbank_rfi.o): In function `clean_filterbank_rfi(dedisp_plan_struct*, unsigned char const*, unsigned long, unsigned long, unsigned char*, int*, float, float, float, float, unsigned long, bool, bool, unsigned long)':
/home/molenaar/upstream/heimdall-astro-code/Pipeline/clean_filterbank_rfi.cu:283: undefined reference to `dedisp_get_channel_count'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/clean_filterbank_rfi.cu:351: undefined reference to `dedisp_get_f0'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/clean_filterbank_rfi.cu:352: undefined reference to `dedisp_get_df'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/clean_filterbank_rfi.cu:354: undefined reference to `dedisp_create_plan'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/clean_filterbank_rfi.cu:359: undefined reference to `dedisp_disable_adaptive_dt'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/clean_filterbank_rfi.cu:363: undefined reference to `dedisp_set_dm_list'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/clean_filterbank_rfi.cu:367: undefined reference to `dedisp_get_max_delay'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/clean_filterbank_rfi.cu:376: undefined reference to `dedisp_execute'
/home/molenaar/upstream/heimdall-astro-code/Pipeline/clean_filterbank_rfi.cu:384: undefined reference to `dedisp_destroy_plan'
collect2: error: ld returned 1 exit status
make[2]: *** [heimdall] Error 1
make[2]: Leaving directory `/home/molenaar/upstream/heimdall-astro-code/Applications'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/molenaar/upstream/heimdall-astro-code'
make: *** [all] Error 2
```

**Comment by loostrum** [comment]
Hmm that looks nasty. Which dedisp are you using?
It worked fine for me with https://github.com/ewanbarr/dedisp-flexi

2018-06-28 18:41 GMT+02:00 Gijs Molenaar <notifications@github.com>:

**Comment by gijzelaerr** [comment]
right, that is a different package. https://github.com/AA-ALERT/spack/issues/30

I had this same issue with KERN packaging I realise now. Luckely they renamed one.
