### ISSUE TITLE
make IRODS package

### ISSUE THREAD

**Issue by gijzelaerr** [AA-ALERT/spack#5]
As per `https://packages.irods.org/`, something like: rpm --import https://packages.irods.org/irods-signing-key.asc wget -qO - https://packages.irods.org/renci-irods.yum.repo \ | tee /etc/yum.repos.d/renci-irods.yum.repo yum install irods-icommands

**Comment by loostrum** [comment]
Maybe do this through ansible? Might be done already.

2018-05-24 16:09 GMT+02:00 Gijs Molenaar <notifications@github.com>:
