### ISSUE TITLE
make tensorflow package

### ISSUE THREAD

**Issue by gijzelaerr** [AA-ALERT/spack#7]
which is hard, maybe just make a ansible rule.

https://www.tensorflow.org/install/install_sources Requires cuDNN, available from NVIDIA developer website with . Files can be provided by Leon Oostrum if needed.

**Comment by loostrum** [comment]
I vote for an ansible rule, an effort has been made to create a spack
tensorflow package (https://gist.github.com/AP97) but it's not fully
supported yet

2018-05-24 16:11 GMT+02:00 Gijs Molenaar <notifications@github.com>:

**Comment by gijzelaerr** [comment]
yeah I agree, for now the only feasible way is a manual pip while making sure the dependencies are sound.

for reference: https://github.com/spack/spack/pull/3244
