### ISSUE TITLE
psrcat package

### ISSUE THREAD

**Issue by gijzelaerr** [AA-ALERT/spack#9]
cd /opt/arts/psrcat/
wget http://www.atnf.csiro.au/people/arts/psrcat/downloads/psrcat_pkg.tar.gz
./makeit

**Comment by loostrum** [comment]
Note: I made a preliminary spack package for psrcat, but the psrcat
maintainers update the psrcat_pkg_tar.gz file regularly so its md5sum keeps
changing.
Hence the default md5sum checking that spack uses won't work.

2018-05-24 16:12 GMT+02:00 Gijs Molenaar <notifications@github.com>:
